// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9rfSea5zaUFFTY6c4RxpFU-kbZYqAAIw',
    appId: '1:958978787094:web:0cf451e595418913987237',
    messagingSenderId: '958978787094',
    projectId: 'testproject-1489d',
    authDomain: 'testproject-1489d.firebaseapp.com',
    storageBucket: 'testproject-1489d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvRlAbhC-fXaB9thZzGCljMcZeIjJlVa8',
    appId: '1:958978787094:android:08a7d2f93a0c1255987237',
    messagingSenderId: '958978787094',
    projectId: 'testproject-1489d',
    storageBucket: 'testproject-1489d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXCDQVB2d8PQSeKiiwDzAGQzIY8-6IqoY',
    appId: '1:958978787094:ios:6a31440196919021987237',
    messagingSenderId: '958978787094',
    projectId: 'testproject-1489d',
    storageBucket: 'testproject-1489d.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXCDQVB2d8PQSeKiiwDzAGQzIY8-6IqoY',
    appId: '1:958978787094:ios:6a31440196919021987237',
    messagingSenderId: '958978787094',
    projectId: 'testproject-1489d',
    storageBucket: 'testproject-1489d.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9rfSea5zaUFFTY6c4RxpFU-kbZYqAAIw',
    appId: '1:958978787094:web:bb347ab9215cdd61987237',
    messagingSenderId: '958978787094',
    projectId: 'testproject-1489d',
    authDomain: 'testproject-1489d.firebaseapp.com',
    storageBucket: 'testproject-1489d.appspot.com',
  );
}
